### ISSUE TITLE
ESbuild option --keep-names (keepNames)

### ISSUE THREAD

**Issue by furanzujin** [r2d2bzh/docker-build-nodejs#6]
Hello there,

In some specific cases, our application needs to check the instance of an object.

**eg**
```javascript
if (error instanceof SpecificError) return handleSpecific(error);
throw error;
```
Though, the current esbuild setup of docker-build-nodejs can append a number to the constructor names.
As described in [this esbuild issue](https://github.com/evanw/esbuild/issues/510), the esbuild option `--keep-names` avoids this behavior.

Would it be possible to enable this option by default?

**Comment by gautaz** [comment]
I'd rather keep this as an option managed by the user through the "esbuildOptions".
A test has been added to ensure this works, see 15e40e71ea23e13869510a3840df12003275cfa2.
